### ISSUE TITLE
easyexcel 模板填充可以实现 表格一对多的情况吗（前半部分是合并的后半部分是分开的） 

### ISSUE THREAD

**Issue by zhangYanWu0** [gongxuanzhang/support-demo#6]
类似这样的
https://image.baidu.com/search/detail?ct=503316480&z=&tn=baiduimagedetail&ipn=d&word=excel%E5%90%88%E5%B9%B6%E5%8D%95%E5%85%83%E6%A0%BC&step_word=&ie=utf-8&in=&cl=2&lm=-1&st=-1&hd=&latest=&copyright=&cs=1790703717,2087409542&os=1925885567,751746678&simid=1790703717,2087409542&pn=2&rn=1&di=7189064908862914561&ln=1594&fr=&fmq=1677635395126_R&ic=&s=undefined&se=&sme=&tab=0&width=&height=&face=undefined&is=0,0&istype=2&ist=&jit=&bdtype=0&spn=0&pi=0&gsm=1e&objurl=https%3A%2F%2Fwww.gpbctv.com%2Fuploads%2F20210619%2Fzip_1624091983xWR89C.jpg&rpstart=0&rpnum=0&adpicid=0&nojc=undefined&dyTabStr=MCwyLDQsMyw2LDEsNSw4LDcsOQ%3D%3D

**Comment by gongxuanzhang** [comment]
如果第一列是固定的就可以

**Comment by zhangYanWu0** [comment]
如果第一列也是需要填充的话是不是就实现不了？  那对于这种需求有什么方法可以实现吗？

**Comment by gongxuanzhang** [comment]
> 

没有办法  只能你写完之后 用拦截器手动合并了
